lane :build_and_release_to_play_store do |options|
  # Get the custom build number
  buildNumber = "v1.0.1"

  # Bundle the app
  gradle(
    task: 'bundle',
    build_type: 'Release',
    project_dir: "android/",
    properties: {
      "versionName" => options[:versionName],
      "versionCode" => buildNumber
    }
  )

  # Upload to Play Store's Internal Testing
  upload_to_play_store(
    package_name: 'com.deploy_rn',
    track: "internal",
    json_key: "./deploy/Conta_de_Servico.json",
    aab: "./android/app/build/outputs/bundle/release/app.aab"
  )
end

desc "Get the custom build number"
private_lane :get_custom_build_number do
  buildNumber = File.read("metadata/buildNumber")

  puts buildNumber

  buildNumber
end