default_platform(:android)

platform :android do 
  lane :beta do
    increment_version_code(
      gradle_file_path: “app/build.gradle”
    )

    gradle(
      task: 'assemble',
      build_type: 'Release'
    )


    upload_to_play_store(track: 'beta')
  end
end


