default_platform(:android)

platform :android do |options|
  lane :beta do
    increment_version_code(
      gradle_file_path: “app/build.gradle”
    )

    gradle(
      task: 'assemble',
      build_type: 'Release'
      properties: {
        "versionName" => options[:versionName],
      }
    )


    upload_to_play_store(track: 'beta')
  end
end


